{% set name = "markdown-customblocks" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markdown-customblocks-{{ version }}.tar.gz
  sha256: f96b72a05c462781ed0d0d01cbbacaa8654a9d94f0ec7d958cd9817f5f28134c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - decorator
    - geocoder
    - markdown
    - mkdocs
    - mkdocs-material
    - python >=3.6
    - pytest
    - responses
    - urllib3 <2
    - yamlns >=0.11

test:
  imports:
    - customblocks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vokimon/markdown-customblocks
  summary: Python Markdown extension to add custom parametrizable and nestable blocks
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
