{% set name = "markdown-customblocks" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markdown-customblocks-{{ version }}.tar.gz
  sha256: 69f86a85ae348c4898a2ca172db309ca8c386c6cc5465e56ed567507c9217b7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - decorator
    - geocoder
    - markdown
    - mkdocs
    - mkdocs-material
    - python >=3.6
    - pytest
    - responses
    - yamlns >=0.11

test:
  imports:
    - customblocks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vokimon/markdown-customblocks
  summary: Python Markdown extension to add custom parametrizable and nestable blocks
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
